/usr/bin/python3 ./../src/collect_demos.py \
  --preview --preview-height 540 --preview-width 920 \
  --disable-side-cam \
  --arm-enable \
  --arm-port /dev/ttyACM0 \
  --udp-port 5005 \
  --ids 1 2 3 4 6 \
  --follower_calib ./../data/calibrations/hand_calibration.json \
  --soft_margin 0.0 \
  --arm-hz 120 \
  --max_step 300 \
  --invert 6 \
  --arm-drain \
  --wheel-pan-enable --wheel-pan-deadzone 0.1 --wheel-pan-gain 0.8
